import { type NextPage } from "next";
import Head from "next/head";
import { SignUp, SignInButton } from "@clerk/nextjs";
import { api } from "~/utils/api";
import SellItem from "./sell-an-item";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center justify-center bg-gray-800">
       
      </main>
    </>
  );
};

export default Home;
